# This is a basic workflow to help you get started with Actions

name: CI

# run every day at hour 6 and 18
on:
  schedule:
    - cron: '*/10 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST https://webhook.gatsbyjs.com/hooks/data_source/publish/0295e66a-725a-40a7-ad00-9f7325eca287
